"""create_registry_tables

Revision ID: bd44babbb822
Revises: 001_users_roles
Create Date: 2026-04-24 16:41:01.080912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = 'bd44babbb822'
down_revision: Union[str, None] = '001_users_roles'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "ltree";')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector";')
    
    op.create_table('interaction_archive',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('schema_ver', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('execution_tree_id', sa.UUID(), nullable=True),
    sa.Column('tree_depth', sa.Integer(), nullable=False),
    sa.Column('tree_path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=True),
    sa.Column('parallel_group_id', sa.UUID(), nullable=True),
    sa.Column('delegation_type', sa.String(length=20), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complete_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('involved_agents', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_immutable', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('agents',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('agent_card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collaborators', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','DEPRECATED','SUSPENDED')", name='ck_agents_status'),
    sa.CheckConstraint("visibility IN ('PUBLIC','DEPARTMENT','PRIVATE')", name='ck_agents_visibility'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('agent_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('certifications',
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('certifier_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('PENDING','PASSED','FAILED','REVOKED')", name='ck_certs_state'),
    sa.ForeignKeyConstraint(['certifier_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('certification_id')
    )
    op.create_table('notices',
    sa.Column('notice_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('target_role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("target_role IN ('all','agent_owner','agent_engineer','trust_ops','governance','evaluator','ethics_liaison','release_manager')", name='ck_notices_role'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notice_id')
    )
    op.create_table('policies',
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('template', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','REVOKED')", name='ck_policies_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_table('workspaces',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE','ARCHIVED','DELETED')", name='ck_ws_state'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('workspace_id')
    )
    op.create_table('agent_certifications',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('certification_id', sa.UUID(), nullable=False),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['certification_id'], ['certifications.certification_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'certification_id')
    )
    op.create_table('agent_policies',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['applied_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.policy_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id', 'policy_id')
    )
    op.create_table('agent_subscription_rules',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('watch_domains', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('watch_intents', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('watch_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('watch_senders', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('watch_roles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('ignore_senders', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('ignore_tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('min_priority', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("min_priority IN ('low','medium','high','critical')", name='ck_asr_priority'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rule_id')
    )
    op.create_table('goals',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("state IN ('ACTIVE','COMPLETED','CANCELLED')", name='ck_goals_state'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.create_table('message_receipts',
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.CheckConstraint("decision IN ('consumed','ignored','expired','failed')", name='ck_mr_decision'),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.agent_id'], ),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_table('conversations',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('schema_ver', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("state IN ('ACTIVE','COMPLETED','ARCHIVED')", name='ck_conv_state'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_table('interactions',
    sa.Column('interaction_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('schema_ver', sa.String(length=10), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('execution_tree_id', sa.UUID(), nullable=True),
    sa.Column('tree_depth', sa.Integer(), nullable=False),
    sa.Column('tree_path', sqlalchemy_utils.types.ltree.LtreeType(), nullable=True),
    sa.Column('parallel_group_id', sa.UUID(), nullable=True),
    sa.Column('delegation_type', sa.String(length=20), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('complete_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('actor_type', sa.String(length=10), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('actor_name', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=10), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('reasoning_trace', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=255), nullable=True),
    sa.Column('tool_input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('involved_agents', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('token_input', sa.Integer(), nullable=True),
    sa.Column('token_output', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("actor_type IN ('user','agent','system')", name='ck_inter_actor_type'),
    sa.CheckConstraint("delegation_type IN ('user_request','orchestration','peer','pipeline','parallel')", name='ck_inter_delegation'),
    sa.CheckConstraint("kind IN ('message','tool_call','tool_result','reasoning','handoff','error')", name='ck_inter_kind'),
    sa.CheckConstraint("state IN ('PENDING','RUNNING','COMPLETED','FAILED','CANCELLED')", name='ck_inter_state'),
    sa.CheckConstraint("target_type IN ('user','agent','broadcast')", name='ck_inter_target_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['interactions.interaction_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('message_headers',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('sender_type', sa.String(length=10), nullable=False),
    sa.Column('sender_name', sa.String(length=255), nullable=True),
    sa.Column('domain', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('target_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('target_roles', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=False),
    sa.Column('execution_tree_id', sa.UUID(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('body_ref', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','critical')", name='ck_mh_priority'),
    sa.CheckConstraint("scope IN ('workspace','department','global')", name='ck_mh_scope'),
    sa.CheckConstraint("sender_type IN ('user','agent','system')", name='ck_mh_sender_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('goal_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('interaction_id', sa.UUID(), nullable=True),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("participant_type IN ('user','agent','system')", name='ck_msg_participant_type'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.goal_id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.workspace_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    op.drop_table('message_headers')
    op.drop_table('interactions')
    op.drop_table('conversations')
    op.drop_table('message_receipts')
    op.drop_table('goals')
    op.drop_table('agent_subscription_rules')
    op.drop_table('agent_policies')
    op.drop_table('agent_certifications')
    op.drop_table('workspaces')
    op.drop_table('policies')
    op.drop_table('notices')
    op.drop_table('certifications')
    op.drop_table('agents')
    op.drop_table('interaction_archive')
    # ### end Alembic commands ###
